# <center> Pandas

## Download dataset ONLY IN COLAB

In [0]:
##### DOWNLOAD DATASET. ONLY IN COLAB !!!
!wget -P ./../data/ https://raw.githubusercontent.com/CenticMurcia/curso-ciencia-datos/master/data/telecom_churn.csv

--2020-01-28 15:53:03--  https://raw.githubusercontent.com/CenticMurcia/curso-ciencia-datos/master/data/telecom_churn.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 279997 (273K) [text/plain]
Saving to: ‘./../data/telecom_churn.csv.1’

telecom_churn.csv.1 100%[===================>] 273.43K  --.-KB/s    in 0.03s

2020-01-28 15:53:04 (8.47 MB/s) - ‘./../data/telecom_churn.csv.1’ saved [279997/279997]

In [0]:
!cd sample_data/
!ls -la

total 16
drwxr-xr-x 1 root root 4096 Jan 13 16:38 .
drwxr-xr-x 1 root root 4096 Jan 28 15:50 ..
drwxr-xr-x 1 root root 4096 Jan 13 16:38 .config
drwxr-xr-x 1 root root 4096 Jan 13 16:38 sample_data

## Import Pandas

In [0]:
import pandas as pd

# Opciones de imppresión
pd.set_option("display.precision", 2)      # Display 2 decimals
pd.set_option('display.max_columns', 1000) # Display all variables

## Create dataframe `df`

In [0]:
df = pd.read_csv('../data/telecom_churn.csv')
df.head()   # Muestra las 5 primeras lineas por defecto, tbn puede ser df.head(3)

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,OH,107,415,No,Yes,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,NJ,137,415,No,No,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,OH,84,408,Yes,No,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,OK,75,415,Yes,No,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False

> # Remember
> ### Column = Variable = Feature = Dimension
> ### Row = Case = Point

## See shape

In [0]:
print("Shape:", df.shape)   # rows X columns
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Shape: (3333, 20)
Number of rows: 3333
Number of columns: 20

## See variables

In [0]:
for d in df.columns:
    print(d)

print(df.columns)

State
Account length
Area code
International plan
Voice mail plan
Number vmail messages
Total day minutes
Total day calls
Total day charge
Total eve minutes
Total eve calls
Total eve charge
Total night minutes
Total night calls
Total night charge
Total intl minutes
Total intl calls
Total intl charge
Customer service calls
Churn
Index(['State', 'Account length', 'Area code', 'International plan',
       'Voice mail plan', 'Number vmail messages', 'Total day minutes',
       'Total day calls', 'Total day charge', 'Total eve minutes',
       'Total eve calls', 'Total eve charge', 'Total night minutes',
       'Total night calls', 'Total night charge', 'Total intl minutes',
       'Total intl calls', 'Total intl charge', 'Customer service calls',
       'Churn'],
      dtype='object')

## Show variable types with `info()`

In [0]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3333 entries, 0 to 3332
Data columns (total 20 columns):
State                     3333 non-null object
Account length            3333 non-null int64
Area code                 3333 non-null int64
International plan        3333 non-null object
Voice mail plan           3333 non-null object
Number vmail messages     3333 non-null int64
Total day minutes         3333 non-null float64
Total day calls           3333 non-null int64
Total day charge          3333 non-null float64
Total eve minutes         3333 non-null float64
Total eve calls           3333 non-null int64
Total eve charge          3333 non-null float64
Total night minutes       3333 non-null float64
Total night calls         3333 non-null int64
Total night charge        3333 non-null float64
Total intl minutes        3333 non-null float64
Total intl calls          3333 non-null int64
Total intl charge         3333 non-null float64
Customer service calls    3333 non-null int64
Churn                     3333 non-null bool
dtypes: bool(1), float64(8), int64(8), object(3)
memory usage: 498.1+ KB
None

## Show statistics of numeric variables

In [0]:
df.describe()

,Account length,Area code,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls
count,3333.00,3333.00,3333.00,3333.00,3333.00,3333.00,3333.00,3333.00,3333.00,3333.00,3333.00,3333.00,3333.00,3333.00,3333.00,3333.00
mean,101.06,437.18,8.10,179.78,100.44,30.56,200.98,100.11,17.08,200.87,100.11,9.04,10.24,4.48,2.76,1.56
std,39.82,42.37,13.69,54.47,20.07,9.26,50.71,19.92,4.31,50.57,19.57,2.28,2.79,2.46,0.75,1.32
min,1.00,408.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,23.20,33.00,1.04,0.00,0.00,0.00,0.00
25%,74.00,408.00,0.00,143.70,87.00,24.43,166.60,87.00,14.16,167.00,87.00,7.52,8.50,3.00,2.30,1.00
50%,101.00,415.00,0.00,179.40,101.00,30.50,201.40,100.00,17.12,201.20,100.00,9.05,10.30,4.00,2.78,1.00
75%,127.00,510.00,20.00,216.40,114.00,36.79,235.30,114.00,20.00,235.30,113.00,10.59,12.10,6.00,3.27,2.00
max,243.00,510.00,51.00,350.80,165.00,59.64,363.70,170.00,30.91,395.00,175.00,17.77,20.00,20.00,5.40,9.00

In [0]:
df['Area code'] = df['Area code'].astype(object)    # Marcamos 'Area code' como columna categórica
df.describe()   # ya no sale 'Area code'

,Account length,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls
count,3333.00,3333.00,3333.00,3333.00,3333.00,3333.00,3333.00,3333.00,3333.00,3333.00,3333.00,3333.00,3333.00,3333.00,3333.00
mean,101.06,8.10,179.78,100.44,30.56,200.98,100.11,17.08,200.87,100.11,9.04,10.24,4.48,2.76,1.56
std,39.82,13.69,54.47,20.07,9.26,50.71,19.92,4.31,50.57,19.57,2.28,2.79,2.46,0.75,1.32
min,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,23.20,33.00,1.04,0.00,0.00,0.00,0.00
25%,74.00,0.00,143.70,87.00,24.43,166.60,87.00,14.16,167.00,87.00,7.52,8.50,3.00,2.30,1.00
50%,101.00,0.00,179.40,101.00,30.50,201.40,100.00,17.12,201.20,100.00,9.05,10.30,4.00,2.78,1.00
75%,127.00,20.00,216.40,114.00,36.79,235.30,114.00,20.00,235.30,113.00,10.59,12.10,6.00,3.27,2.00
max,243.00,51.00,350.80,165.00,59.64,363.70,170.00,30.91,395.00,175.00,17.77,20.00,20.00,5.40,9.00

## Show statistics of categoric variables

In [0]:
df.describe(include=['object', 'bool'])   # Estadísticas de variables categóricas y booleanas

       State  Area code International plan Voice mail plan  Churn
count   3333       3333               3333            3333   3333
unique    51          3                  2               2      2
top       WV        415                 No              No  False
freq     106       1655               3010            2411   2850

In [0]:
df['Area code'].describe()

0       415
1       415
2       415
3       408
4       415
       ...
3328    415
3329    415
3330    510
3331    510
3332    415
Name: Area code, Length: 3333, dtype: object

## Select 1 variable (serie)

In [0]:
df.State

0       KS
1       OH
2       NJ
3       OH
4       OK
        ..
3328    AZ
3329    WV
3330    RI
3331    CT
3332    TN
Name: State, Length: 3333, dtype: object

In [0]:
df["State"]

0       KS
1       OH
2       NJ
3       OH
4       OK
        ..
3328    AZ
3329    WV
3330    RI
3331    CT
3332    TN
Name: State, Length: 3333, dtype: object

## Select multiple variables

In [0]:
df[["State", "Account length", "Area code"]]

     State  Account length Area code
0       KS             128       415
1       OH             107       415
2       NJ             137       415
3       OH              84       408
4       OK              75       415
...    ...             ...       ...
3328    AZ             192       415
3329    WV              68       415
3330    RI              28       510
3331    CT             184       510
3332    TN              74       415

[3333 rows x 3 columns]

## Numerical variable -> Min, max, mean, median, std, ...

In [0]:
df['Account length'].min()

1

In [0]:
df['Account length'].max()

243

In [0]:
df['Account length'].mean()

101.06480648064806

In [0]:
df['Account length'].median()

101.0

In [0]:
df['Account length'].std()

39.822105928595604

## Categorical variable -> Count unique values

In [0]:
df['Churn'].value_counts()

False    2850
True      483
Name: Churn, dtype: int64

In [0]:
df['Churn'].value_counts(normalize=True)

False    0.86
True     0.14
Name: Churn, dtype: float64

In [0]:
# Show top 10 in a dataframe
pd.DataFrame({  'Recuento':   df['State'].value_counts(),
                'Porcentaje': df['State'].value_counts(normalize=True) * 100
             }).head(5)

    Recuento  Porcentaje
WV       106        3.18
MN        84        2.52
NY        83        2.49
AL        80        2.40
WI        78        2.34

## Categorial varaibles -> Cross table
#### Also known as Contingency table

In [0]:
pd.crosstab(df['Churn'], df['International plan'])

International plan    No  Yes
Churn
False               2664  186
True                 346  137

In [0]:
pd.crosstab(df['Churn'], df['International plan'], margins=True)

International plan    No  Yes   All
Churn
False               2664  186  2850
True                 346  137   483
All                 3010  323  3333

In [0]:
pd.crosstab(df['Churn'], df['Voice mail plan'], normalize=True)

Voice mail plan    No   Yes
Churn
False            0.60  0.25
True             0.12  0.02

## Numeric & Categorial varaibles -> Pivot table

In [0]:
df.pivot_table(['Total day calls', 'Total eve calls', 'Total night calls'],
               ['State'], aggfunc='mean').head()

       Total day calls  Total eve calls  Total night calls
State
AK               95.27            96.58              97.35
AL               99.10            98.46              98.61
AR              102.15            97.84              99.05
AZ              100.11           102.41              99.98
CA              104.50           103.09              99.21

In [0]:
df.pivot_table(['Total day calls', 'Total eve calls', 'Total night calls'],
               ['State', "Churn"], aggfunc='mean').head()

             Total day calls  Total eve calls  Total night calls
State Churn
AK    False            95.59            96.39              97.55
      True             90.00            99.67              94.00
AL    False            99.39            99.25              98.40
      True             96.50            91.38             100.50
AR    False           101.91            94.84              96.34

# <center> Filters

## 1 Filter

In [0]:
df[df['Churn'] == True]
df[df['State'] == 'MD']
df[df['Total day calls'] > 150].head(5)

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
164,OK,146,415,No,No,0,206.3,151,35.07,148.6,89,12.63,167.2,91,7.52,6.1,3,1.65,1,False
315,MA,39,408,No,No,0,60.4,158,10.27,306.2,120,26.03,123.9,46,5.58,12.4,3,3.35,1,False
468,AZ,86,415,No,Yes,32,70.9,163,12.05,166.7,121,14.17,244.9,105,11.02,11.1,5,3.00,3,False
580,IN,113,415,No,No,0,209.4,151,35.60,347.3,113,29.52,246.0,116,11.07,7.4,2,2.00,1,True
1057,WV,86,415,No,Yes,38,123.0,158,20.91,133.9,119,11.38,138.2,103,6.22,13.3,4,3.59,1,False

In [0]:
df[(df['Total day minutes'] > 150) & (df['Total day charge'] < 150)].tail(3)

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
3330,RI,28,510,No,No,0,180.8,109,30.74,288.8,58,24.55,191.9,91,8.64,14.1,6,3.81,2,False
3331,CT,184,510,Yes,No,0,213.8,105,36.35,159.6,84,13.57,139.2,137,6.26,5.0,10,1.35,2,False
3332,TN,74,415,No,Yes,25,234.4,113,39.85,265.9,82,22.60,241.4,77,10.86,13.7,4,3.70,0,False

In [0]:
df[df['Voice mail plan'] == 'Yes'].head(3)

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,OH,107,415,No,Yes,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
6,MA,121,510,No,Yes,24,218.2,88,37.09,348.5,108,29.62,212.6,118,9.57,7.5,7,2.03,3,False

## Multiple filters

In [0]:
df[ (df['Churn']==False) & (df['International plan']=='No')]

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,OH,107,415,No,Yes,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,NJ,137,415,No,No,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
6,MA,121,510,No,Yes,24,218.2,88,37.09,348.5,108,29.62,212.6,118,9.57,7.5,7,2.03,3,False
8,LA,117,408,No,No,0,184.5,97,31.37,351.6,80,29.89,215.8,90,9.71,8.7,4,2.35,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3327,SC,79,415,No,No,0,134.7,98,22.90,189.7,68,16.12,221.4,128,9.96,11.8,5,3.19,2,False
3328,AZ,192,415,No,Yes,36,156.2,77,26.55,215.5,126,18.32,279.1,83,12.56,9.9,6,2.67,2,False
3329,WV,68,415,No,No,0,231.1,57,39.29,153.4,55,13.04,191.3,123,8.61,9.6,4,2.59,3,False
3330,RI,28,510,No,No,0,180.8,109,30.74,288.8,58,24.55,191.9,91,8.64,14.1,6,3.81,2,False
3332,TN,74,415,No,Yes,25,234.4,113,39.85,265.9,82,22.60,241.4,77,10.86,13.7,4,3.70,0,False

# <center> Dataframe Modification

# <center> Summary
- The data table is a Pandas **dataframe**
- The data column is a Pandas **series**
- We can obtain information of the **dataset**:
  - 10 top rows: `df.head(10)`
  - Number of rows & variables: `df.shape`
  - Names of variables: `df.columns`
  - Types of variables: `df.info()`
  - Stats of numerical variables: `df.describe()`
  - Stats of numerical variables: `df.describe(include=['object', 'bool'])`
- Information of **numerical variables**:
  - Minimum `df.num_var.min()`
  - Maximun `df.num_var.max()`
  - Mean `df.num_var.mean()`
  - Median `df.num_var.median()`
  - Std `df.variable.std()`
- Information of **categorical variables**:
  - Unique values (count): `df.cat_var.value_counts()`
  - Unique values (percent): `df.cat_var.value_counts(normalize=True)`
  - 2 categorial vars (count): `pd.crosstab(df.cat_var1, df.cat_var2, margins=True)`
  - 2 categorial vars (percen): `pd.crosstab(df.cat_var1, df.cat_var2, margins=True, normalize=True)`
- Information of **numerical & categorial variables**:
  - Pivot table: `df.pivot_table([num_var1, num_var2, ...], [cat_var1, cat_var2], aggfunc='mean')`
- **Fitering rows**:
  - One filter: `df[ condition ]`
  - Multiple filters: `df[ (condition1) & (condition2)]`

# <center> Bonus: Pandas Profiling

In [0]:
from pandas_profiling import ProfileReport

In [0]:
profile = ProfileReport(df)

/usr/local/lib/python3.6/dist-packages/pandas_profiling/describe.py:392: FutureWarning: The join_axes-keyword is deprecated. Use .reindex or .reindex_like on the result to achieve the same functionality.
  variable_stats = pd.concat(ldesc, join_axes=pd.Index([names]), axis=1)

In [0]:
profile

# <center> Fin